### ISSUE TITLE
Is this better than jacobSingh/tabwrangler? If so, how?

### ISSUE THREAD

**Issue by Wizek** [sonntag/tabshepherd#8]
https://github.com/jacobSingh/tabwrangler

**Comment by sonntag** [comment]
I wouldn't necessarily say "better."  They both work, and they both accomplish the same task in very similar manners.  Tab Shepherd has a different tab closing engine which is more reactive, where as Tab Wrangler uses a time-based approach.  The reactive approach tends to have a lot less bugs that appear because of lag in Chrome itself and things feel more responsive, but both work.

Tab Wrangler has also been updated more recently to have some newer features, however I should have an update out to Tab Shepherd soon.  This update will have all of the missing features, along with a few new features that aren't available in Tab Wrangler.

When I was using Tab Wrangler over 2 years ago, there were a number of bugs.  I rewrote a bunch of it to get rid of those bugs, but was not able to get the developer to pull my merge requests, so I created a new version of the app.  Hopefully someday we'll be able to merge the two together so we don't have to keep duplicating the work.

**Comment by Wizek** [comment]
What do you mean by "time-based approach" and "more reactive approach"?

Thanks for detailing the history and your motivations behind tabshepherd! Do you think you could include this or something similar in the readme? I think others might be confused too when they stumble upon these extensions.

**Comment by sonntag** [comment]
Tab Wrangler's approach to closing tabs uses a timer which fires every 5 seconds to check if any tabs need to be closed.  That means even if the user isn't actively using Chrome, it will still use processing resources every 5 seconds to perform it's check.  This is what I mean by a time-based approach.  It is a simpler algorithm to implement, however it uses a lot of unnecessary CPU time, and there are a number of weird synchronization bugs that can occur if it takes longer than 5 seconds to run it's tab closing process (which I observed happen when I was watching movies).  I also find it very difficult to add new features to Tab Wrangler's tab closing process.

Tab Shepherd uses an approach where things can only happen when a user performs an action.  For example, whenever a new tab is opened, a routine is run to see if max tabs is exceeded.  If it is, then it will schedule the oldest tab to be closed in the future. If the user remains idle and that time expires, then an event will fire which will close the tab.  If the user intervenes, for example by closing a tab, then the tab will be unscheduled.  This approach is more reactive because nothing happens until a user performs an action.  This type of approach does not have any synchronization issues, and it has proven to be easy to maintain.

I'll try to add something to the readme later, along with a feature comparison list.

**Comment by Wizek** [comment]
I see what you mean now. Thanks!
